version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=curso-node-e2e
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  postgres-e2e:
    image: postgres:13
    environment:
      - POSTGRES_DB=db-e2e
      - POSTGRES_USER=e2e
      - POSTGRES_PASSWORD=passworde2e
    ports:
      - 5434:5432

volumes:
  postgres_data:
    external: true

