name: API CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:16
    services:
      postgres-e2e:
        image: postgres:13
        env:
          POSTGRES_USER: e2e
          POSTGRES_PASSWORD: passworde2e
          POSTGRES_DB: db-e2e
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run e2e:ci
        env:
          PORT: 3000
          DATABASE_URL: postgres://e2e:passworde2e@postgres-e2e:5432/db-e2e
          API_KEY: 79823
          JWT_SECRET: s3cr3t
          SMTP_EMAIL: your@email.com
          SMTP_PASSWORD: password-email
    